/**
 * Shared session/agent payload types.
 *
 * These live under `runtime-types/` so domain modules (`src/agent/**`) can
 * reference them without importing `managers/**`. Manager modules re-export
 * them to preserve their existing public surface.
 */

import type { AgentRetryState } from "./agent-retry.js";
import type { AgentStatus } from "./agent-status.js";
import type { TokenUsage } from "./token-usage.js";
import type { ContentPart } from "@tanstack/ai";

/** Active agent mode — mutually exclusive modes for the agent. */
export type AgentMode = "normal" | "auto" | "plan";

/** L1 runtime status surface projected to AgentSession `state` channel. */
export interface AgentL1State {
  status: AgentStatus;
  /** Agent display name (lets remote clients track renames via the state channel). */
  name: string;
  error: string;
  pendingApprovalCount: number;
  /** Present while a recoverable LLM failure is being retried (cleared once the stream recovers). */
  retry?: AgentRetryState | null;
}

/** Content accepted by the steer / follow-up queues. */
export type QueuedMessageContent = string | ContentPart[];

export interface QueuedMessagesSnapshot {
  steer: QueuedMessageContent[];
  followUp: QueuedMessageContent[];
}

/** Payload-carrying usage view for Emitter / AgentSession `usage` channel. */
export interface UsageChangeSnapshot {
  total: TokenUsage;
  window: TokenUsage;
  percent: number;
  tokenLimit: number;
  cost: number;
  /** Cumulative wall-clock time of measured main-loop LLM calls (ms). */
  llmDurationMs: number;
  /** Output tokens generated by the measured main-loop LLM calls (basis for tok/s). */
  llmOutputTokens: number;
}
