/**
 * Compaction summary markers and detectors (shared; no cut-point imports).
 *
 * ⚠️ These markers are how the compaction chain recognizes its own checkpoints:
 * `isCompactionSummaryText` matches ANY user message whose text starts with
 * `[CONVERSATION SUMMARY]`, and `findOuterEndIndex` treats a solo-line
 * `[END SUMMARY]` as the closing boundary. A *user* message that forges these
 * markers would be misread as a compaction checkpoint, which can:
 *   - make `isLatestDurableMessageCompactionSummary` skip auto-compact
 *     (the session silently stops compacting), and/or
 *   - make `cut-point` / `extractCompactionSummaryBody` swallow or truncate
 *     the message body at a forged `[END SUMMARY]` line.
 *
 * Therefore every user-text entry point MUST run
 * {@link assertNotCompactionSummaryInput} before the message lands on the
 * channel. The only legitimate producers of these markers are compaction
 * itself (`createCompactionSummaryUIMessage`) and the model inside a
 * compaction run (formatted by {@link formatCompactionSummaryContent}).
 */

import { isContextUIMessage } from "../turn-context/turn-context-message.js";

import { extractTextFromContent } from "./message-utils.js";

import type { ContentPart, ModelMessage, UIMessage } from "@tanstack/ai";

export const CONVERSATION_SUMMARY_START = "[CONVERSATION SUMMARY]";
export const CONVERSATION_SUMMARY_END = "[END SUMMARY]";

export function isCompactionSummaryText(text: string | undefined | null): boolean {
  if (!text) return false;
  return text.trimStart().startsWith(CONVERSATION_SUMMARY_START);
}

function extractFirstText(content: string | readonly ContentPart[]): string | undefined {
  if (typeof content === "string") return content;
  for (const part of content) {
    if (part.type !== "text") continue;
    const value = (part as { content?: unknown; text?: unknown }).content ?? (part as { text?: unknown }).text;
    return typeof value === "string" ? value : undefined;
  }
  return undefined;
}

/**
 * Reject user-authored text that forges the compaction summary markers.
 *
 * Compaction checkpoints are detected purely by marker matching (see the
 * header note), so any message whose first text starts with
 * `[CONVERSATION SUMMARY]` would be treated as a compaction checkpoint and
 * break auto-compact / cut-point detection. Call this at every user-message
 * entry point (send / follow-up / force-submit) before the message reaches
 * the channel.
 *
 * @throws if the input begins with {@link CONVERSATION_SUMMARY_START}
 */
export function assertNotCompactionSummaryInput(content: string | readonly ContentPart[]): void {
  const text = extractFirstText(content);
  if (text !== undefined && isCompactionSummaryText(text)) {
    throw new Error(
      `Input starts with the reserved compaction marker "${CONVERSATION_SUMMARY_START}" and ` +
        "would be misread as a compaction summary checkpoint. Please reword the message."
    );
  }
}

export function isCompactionSummaryModelMessage(message: ModelMessage): boolean {
  if (message.role !== "user") return false;
  return isCompactionSummaryText(extractTextFromContent(message.content));
}

export function isCompactionSummaryUIMessage(message: UIMessage): boolean {
  if (message.role !== "user") return false;
  const textPart = message.parts.find((part) => part.type === "text");
  if (!textPart || textPart.type !== "text") return false;
  return isCompactionSummaryText(textPart.content);
}

/**
 * True when the latest durable channel message is already a compaction SUMMARY.
 * Skips trailing synthetic `<ctx kind=...>` so a just-appended checkpoint is
 * detected even if turn-context lands after it.
 *
 * Used to stop auto-compact from stacking a second SUMMARY before any new
 * user / assistant / tool work (window usage is 0 after compact, so the
 * token estimator would otherwise re-trigger immediately).
 */
export function isLatestDurableMessageCompactionSummary(messages: UIMessage[]): boolean {
  for (let i = messages.length - 1; i >= 0; i--) {
    const message = messages[i]!;
    if (isContextUIMessage(message)) continue;
    return isCompactionSummaryUIMessage(message);
  }
  return false;
}

/**
 * Find the outer closing marker: the **last** `[END SUMMARY]` that appears solo on its
 * own line (the real wrapper generated by {@link formatCompactionSummaryContent}).
 *
 * Bodies may quote the markers verbatim (e.g. a summary describing the compaction
 * format itself) — those inline occurrences are line-embedded and never treated as
 * the closing marker, so the body is not truncated at a nested `[END SUMMARY]`.
 * This also fixes streaming: nested markers that arrive before the real outer END
 * do not freeze the extracted body at a premature cut.
 *
 * @returns index of the outer closing marker (start of `[END SUMMARY]`), or -1 if none found
 */
function findOuterEndIndex(trimmed: string): number {
  let lastSoloEnd = -1;
  let searchFrom = 0;
  for (;;) {
    const idx = trimmed.indexOf(CONVERSATION_SUMMARY_END, searchFrom);
    if (idx === -1) break;
    const lineStart = trimmed.lastIndexOf("\n", idx - 1) + 1;
    let lineEnd = trimmed.indexOf("\n", idx);
    if (lineEnd === -1) lineEnd = trimmed.length;
    const line = trimmed.slice(lineStart, lineEnd);
    if (line.trim() === CONVERSATION_SUMMARY_END) {
      lastSoloEnd = idx;
    }
    searchFrom = idx + CONVERSATION_SUMMARY_END.length;
  }
  return lastSoloEnd;
}

/** Whether the text contains a solo-line outer closing marker. */
export function hasOuterEndMarker(text: string | undefined | null): boolean {
  if (!text) return false;
  return findOuterEndIndex(text.trimStart()) !== -1;
}

/**
 * Extract the summary body between markers.
 * - Wrapped text → body between {@link CONVERSATION_SUMMARY_START} and the outer
 *   closing marker (last solo-line `[END SUMMARY]`).
 * - Streaming (no solo closing marker yet) → text after start marker to end of string
 * - Unwrapped plain text → trimmed passthrough (e.g. reactive before re-wrap)
 */
export function extractCompactionSummaryBody(text: string): string | undefined {
  const trimmed = text.trimStart();
  if (!trimmed.startsWith(CONVERSATION_SUMMARY_START)) {
    const plain = text.trim();
    return plain || undefined;
  }

  const endIndex = findOuterEndIndex(trimmed);
  const body =
    endIndex === -1
      ? trimmed.slice(CONVERSATION_SUMMARY_START.length)
      : trimmed.slice(CONVERSATION_SUMMARY_START.length, endIndex);
  const result = body.trim();
  return result || undefined;
}

export function formatCompactionSummaryContent(summary: string): string {
  return `${CONVERSATION_SUMMARY_START}

${summary}

${CONVERSATION_SUMMARY_END}

Continue if you have next steps, or stop and ask for clarification if you are unsure how to proceed.`;
}
