import { defineConfig } from "tsdown";

export default defineConfig([
  {
    entry: [
      "src/index.ts",
      "src/utils/lite-diff.ts",
      "src/utils/lite-diff-highlight.ts",
      "src/utils/input-feedback-queue.ts",
      "src/utils/workspace-scroll.ts",
      "src/utils/workspace-git-diff.ts",
      "src/utils/workspace-git-info.ts",
      "src/utils/workspace-diff-stats.ts",
      "src/utils/workspace-diff-tree.ts",
      "src/utils/workspace-file-search.ts",
      "src/utils/streaming-output-lines.ts",
      "src/utils/format-usage.ts",
      "src/utils/file-icons.ts",
      "src/utils/tool-activity-summary.ts",
      "src/utils/project-transcript.ts",
      "src/utils/user-message-images.ts",
      "src/utils/attachment-hash.ts",
      "src/utils/apply-app-config.ts",
      "src/utils/get-messages.ts",
      "src/utils/user-input-helpers.ts",

      "src/utils/streaming-ingest.ts",
    ],
    format: ["esm"],
    dts: true,
    clean: true,
    shims: true,
    deps: {
      neverBundle: [
        "ink",
        "react",
        "react/jsx-runtime",
        "react/jsx-dev-runtime",
        "@my-agent/core",
        "@my-agent/node",
        "chalk",
        "ink-stream-markdown",
        "@git-diff-view/cli",
        "@git-diff-view/file",
        "@git-diff-view/core",
        "@git-diff-view/lowlight",
        "diff",
        "@m234/nerd-fonts",
      ],
    },
  },
]);
