import { calculateCost, type TokenUsage } from "../../runtime-types/token-usage.js";
import { Emitter } from "../../utils/emitter.js";

import type { ModelCapability, ModelPricing } from "../../models/types.js";

export { extractTanStackProvider, extractTanStackUsage } from "../../runtime-types/token-usage.js";

// ============================================================================
// UsageTracker
// ============================================================================

const emptyUsage = (): TokenUsage => ({
  inputTokens: 0,
  outputTokens: 0,
  totalTokens: 0,
  cacheReadTokens: 0,
  cacheWriteTokens: 0,
  reasoningTokens: 0,
});

export interface UsageSnapshot {
  usage: TokenUsage;
  costUsd?: number;
}

/** Payload-carrying usage view for Emitter / AgentSession `usage` channel. */
export interface UsageChangeSnapshot {
  total: TokenUsage;
  window: TokenUsage;
  percent: number;
  tokenLimit: number;
  cost: number;
  /** Cumulative wall-clock time of measured main-loop LLM calls (ms). */
  llmDurationMs: number;
  /** Output tokens generated by the measured main-loop LLM calls (basis for tok/s). */
  llmOutputTokens: number;
}

type UsageTrackerEvents = {
  change: UsageChangeSnapshot;
};

/**
 * Tracks per-step context window fill and lifetime token usage for a managed agent.
 */
export class UsageTracker {
  /** Current context window fill (input replaced each step; output accumulated per turn). */
  private window: TokenUsage = emptyUsage();

  /** Lifetime totals across compaction cycles. */
  private total: TokenUsage = emptyUsage();

  private totalCostUsd = 0;
  private pricing: ModelPricing | null = null;
  private capabilities: ModelCapability[] = [];
  private tokenLimit = 0;

  /** Cumulative wall-clock time of measured main-loop LLM calls (ms). */
  private totalLlmMs = 0;
  /** Output tokens generated by the measured main-loop LLM calls. */
  private totalLlmOutputTokens = 0;
  /** Cost of the most recent accumulation (main step or side query), for per-call logging. */
  private lastCallCostUsd = 0;
  /** Reasoning tokens of the most recent main step, for per-call logging. */
  private lastCallReasoningTokens = 0;

  private readonly events = new Emitter<UsageTrackerEvents>();

  /** Subscribe to usage change events (payload is a serializable snapshot). */
  on<K extends keyof UsageTrackerEvents>(type: K, listener: (payload: UsageTrackerEvents[K]) => void): () => void {
    return this.events.on(type, listener);
  }

  /** Update window usage from a main run step and accumulate into lifetime totals. */
  updateWindowUsage(usage: TokenUsage, pricing?: ModelPricing | null): void {
    const prev = this.window;
    const resolvedPricing = pricing ?? this.pricing;

    this.window = {
      inputTokens: usage.inputTokens,
      outputTokens: prev.outputTokens + usage.outputTokens,
      totalTokens: 0,
      cacheReadTokens: usage.cacheReadTokens ?? 0,
      cacheWriteTokens: usage.cacheWriteTokens ?? 0,
      reasoningTokens: (prev.reasoningTokens ?? 0) + (usage.reasoningTokens ?? 0),
    };
    this.window.totalTokens = this.window.inputTokens + this.window.outputTokens;
    this.lastCallReasoningTokens = usage.reasoningTokens ?? 0;

    this.lastCallCostUsd = this.accumulateTotal(usage, resolvedPricing);
    this.emitChange();
  }

  /** Add usage to lifetime totals only (side queries, title generation, etc.). */
  addTotal(usage: TokenUsage, pricing?: ModelPricing | null): void {
    this.lastCallCostUsd = this.accumulateTotal(usage, pricing ?? this.pricing);
    this.emitChange();
  }

  /**
   * Add usage plus a precomputed cost to lifetime totals without re-pricing.
   * Used when aggregating a subagent's totals into its parent: the subagent
   * already computed each call's cost with its own model's pricing, so the
   * parent must carry the cost over instead of re-computing it at the parent's
   * (possibly different) rate.
   */
  addTotalWithCost(usage: TokenUsage, costUsd: number): void {
    this.accumulateTotal(usage, null);
    this.totalCostUsd += Number.isFinite(costUsd) && costUsd > 0 ? costUsd : 0;
    this.lastCallCostUsd = 0;
    this.emitChange();
  }

  /**
   * Record one measured main-loop LLM call: its wall-clock duration and generated output tokens.
   *
   * Together these yield a generation-rate basis (tok/s) that only counts calls whose
   * duration is actually known — unmeasured aggregation (e.g. subagent totals added via
   * {@link addTotal}) and side-query calls (titles, summaries, memory selection) are
   * excluded, keeping the rate a faithful measure of the agent's own generation speed.
   */
  addLlmCall(durationMs: number, outputTokens: number): void {
    if (!Number.isFinite(durationMs) || durationMs <= 0) return;
    this.totalLlmMs += durationMs;
    this.totalLlmOutputTokens += Number.isFinite(outputTokens) && outputTokens > 0 ? outputTokens : 0;
    this.emitChange();
  }

  getLlmDurationMs(): number {
    return this.totalLlmMs;
  }

  getLlmOutputTokens(): number {
    return this.totalLlmOutputTokens;
  }

  private accumulateTotal(usage: TokenUsage, pricing: ModelPricing | null | undefined): number {
    this.total = {
      inputTokens: this.total.inputTokens + usage.inputTokens,
      outputTokens: this.total.outputTokens + usage.outputTokens,
      totalTokens: 0,
      cacheReadTokens: (this.total.cacheReadTokens ?? 0) + (usage.cacheReadTokens ?? 0),
      cacheWriteTokens: (this.total.cacheWriteTokens ?? 0) + (usage.cacheWriteTokens ?? 0),
      reasoningTokens: (this.total.reasoningTokens ?? 0) + (usage.reasoningTokens ?? 0),
    };
    this.total.totalTokens = this.total.inputTokens + this.total.outputTokens;

    if (!pricing) return 0;
    const callCost = calculateCost(usage, pricing);
    this.totalCostUsd += callCost;
    return callCost;
  }

  getWindowUsage(): Readonly<TokenUsage> {
    return this.window;
  }

  getTotal(): Readonly<TokenUsage> {
    return this.total;
  }

  getTotalCostUsd(): number {
    return this.totalCostUsd;
  }

  /** Cost of the most recent accumulation (0 when no pricing was configured). */
  getLastCallCostUsd(): number {
    return this.lastCallCostUsd;
  }

  /** Reasoning tokens of the most recent main step. */
  getLastCallReasoningTokens(): number {
    return this.lastCallReasoningTokens;
  }

  setTotalCostUsd(cost: number): void {
    this.totalCostUsd = cost;
    this.emitChange();
  }

  setPricing(pricing: ModelPricing): void {
    this.pricing = pricing;
  }

  getPricing(): ModelPricing | null {
    return this.pricing;
  }

  setCapabilities(caps: ModelCapability[]): void {
    this.capabilities = caps;
  }

  hasCapability(cap: ModelCapability): boolean {
    if (this.capabilities.length === 0) return true;
    return this.capabilities.includes(cap);
  }

  setTokenLimit(limit: number): void {
    this.tokenLimit = limit;
  }

  getTokenLimit(): number {
    return this.tokenLimit;
  }

  getTokenLimitPercent(): number {
    if (this.tokenLimit <= 0) return 0;
    return Math.min(100, (this.window.inputTokens / this.tokenLimit) * 100);
  }

  resetWindow(): void {
    this.window = emptyUsage();
    this.emitChange();
  }

  reset(): void {
    this.window = emptyUsage();
    this.total = emptyUsage();
    this.totalCostUsd = 0;
    this.totalLlmMs = 0;
    this.totalLlmOutputTokens = 0;
    this.emitChange();
  }

  snapshot(pricing?: ModelPricing | null): UsageSnapshot {
    const resolved = pricing ?? this.pricing;
    return {
      usage: { ...this.total },
      ...(resolved ? { costUsd: this.totalCostUsd || calculateCost(this.total, resolved) } : {}),
    };
  }

  /** Full UI-oriented usage snapshot (totals + window fill). */
  getChangeSnapshot(): UsageChangeSnapshot {
    return {
      total: { ...this.total },
      window: { ...this.window },
      percent: this.getTokenLimitPercent(),
      tokenLimit: this.tokenLimit,
      cost: this.totalCostUsd,
      llmDurationMs: this.totalLlmMs,
      llmOutputTokens: this.totalLlmOutputTokens,
    };
  }

  private emitChange(): void {
    this.events.emit("change", this.getChangeSnapshot());
  }
}
